### ISSUE TITLE
今天安装的命令行monica   新建了一个 然后 启动实例后   实例的控制面板显示不出来

### ISSUE THREAD

**Issue by yangguangwuwu** [Monibuca/monica#17]
今天安装的命令行monica   新建了一个 然后 启动实例后   实例的控制面板显示不出来
![20210622155243](https://user-images.githubusercontent.com/24450871/122885707-e6b02200-d371-11eb-9966-fa00a9d7286e.png)
![20210622155122](https://user-images.githubusercontent.com/24450871/122885725-ec0d6c80-d371-11eb-92d4-b975a27914b5.png)

**Comment by rainmanwy** [comment]
一样的问题+1

**Comment by lovederh** [comment]
+1

**Comment by lovederh** [comment]
下载源码后, 可以了

**Comment by yangguangwuwu** [comment]
@lovederh 重新npm i -g @langhuihui/monica   吗？

**Comment by yangguangwuwu** [comment]
@lovederh 依旧不行

**Comment by lovederh** [comment]
> @lovederh 依旧不行

我是下载的这个源码, 然后运行的, 按官网文档操作的也是出不来

**Comment by yangguangwuwu** [comment]
看来是 官方 推的  npm仓库的代码 有问题
